# Generated by Django 5.1.1 on 2024-11-02 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории одежды')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория одежды',
                'verbose_name_plural': 'Категории одежды',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID цвета')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено')], max_length=20, verbose_name='Статус оплаты')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=20, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID одежды')),
                ('model', models.CharField(max_length=100, verbose_name='Название модели')),
                ('target', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс'), ('C', 'Детский')], max_length=1, verbose_name='Пол')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Средний рейтинг')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Бренд', to='MainShop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='MainShop.clothingcategory')),
            ],
            options={
                'verbose_name': 'Модель одежды',
                'verbose_name_plural': 'Модель одежды',
            },
        ),
        migrations.CreateModel(
            name='ColorsClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.clothing', verbose_name='Одежда')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвета_Одежда',
                'verbose_name_plural': 'Цвета_Одежды',
            },
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID детали заказа')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price_when_ordering', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена при заказе')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_clothes', to='MainShop.clothing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='MainShop.orders')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('color_clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.colorsclothing', verbose_name='Одежда')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('colors_clothing', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='MainShop.colorsclothing', verbose_name='Цвета_одежды')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.sizes', verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MainShop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.colorsclothing')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
