# Generated by Django 5.1.1 on 2024-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории одежды')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория одежды',
                'verbose_name_plural': 'Категории одежды',
            },
        ),
    ]
