# Generated by Django 5.1.1 on 2024-09-24 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории одежды')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория одежды',
                'verbose_name_plural': 'Категории одежды',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено')], max_length=20, verbose_name='Статус оплаты')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=20, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID одежды')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sex', models.CharField(max_length=100, verbose_name='Пол')),
                ('color', models.CharField(max_length=40, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Количество в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='MainShop.clothingcategory')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID детали заказа')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price_when_ordering', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена при заказе')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_clothes', to='MainShop.clothing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='MainShop.orders')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID корзины')),
                ('count', models.IntegerField(verbose_name='Количество в корзине')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_cart', to='MainShop.clothing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
