# Generated by Django 5.1.1 on 2024-10-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID цвета')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='size',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.ManyToManyField(to='MainShop.color', verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sizes',
            field=models.ManyToManyField(to='MainShop.sizes', verbose_name='Размеры'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.clothing', verbose_name='Одежда')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.color', verbose_name='Цвет')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.sizes', verbose_name='Размер')),
            ],
        ),
    ]
