# Generated by Django 5.1.1 on 2024-09-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID одежды')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sex', models.CharField(max_length=100, verbose_name='Пол')),
                ('color', models.CharField(max_length=40, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Количество в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='MainShop.clothingcategory')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID корзины')),
                ('count', models.IntegerField(verbose_name='Количество в корзине')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_cart', to='MainShop.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено')], max_length=20, verbose_name='Статус оплаты')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=20, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID детали заказа')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price_when_ordering', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена при заказе')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_clothes', to='MainShop.clothing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='MainShop.orders')),
            ],
        ),
    ]
