# Generated by Django 5.1.1 on 2024-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0002_clothing_cart_orders_ordersdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordersdetail',
            options={'verbose_name': 'Детали заказа', 'verbose_name_plural': 'Детали заказов'},
        ),
    ]
