# Generated by Django 5.1.1 on 2024-10-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0002_alter_pricehistory_clothing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='clothing',
            new_name='color_clothing',
        ),
    ]
