# Generated by Django 5.1.1 on 2024-11-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0002_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'stock')},
        ),
    ]
