# Generated by Django 5.1.3 on 2024-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0002_countrymanufacture_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='largecategory',
            name='eng_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
