# Generated by Django 5.1.3 on 2024-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0003_largecategory_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingcategory',
            name='eng_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Category (EN)'),
            preserve_default=False,
        ),
    ]
