# Generated by Django 5.1.1 on 2024-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0003_rename_product_cartitem_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категория одежды',
            },
        ),
    ]
