# Generated by Django 5.1.1 on 2024-10-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0003_remove_clothing_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
    ]
