# Generated by Django 5.1.2 on 2024-11-02 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0003_rename_clothing_pricehistory_color_clothing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorsclothing',
            options={'verbose_name': 'Цвета_Одежда', 'verbose_name_plural': 'Цвета_Одежды'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MainShop.cart')),
                ('colors_clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='MainShop.colorsclothing')),
            ],
        ),
    ]
