# Generated by Django 5.1.1 on 2024-11-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0004_largecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsclothing',
            name='large_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainShop.largecategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
