# Generated by Django 5.1.1 on 2024-10-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0005_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
    ]
