# Generated by Django 5.1.1 on 2024-11-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0005_colorsclothing_large_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='largecategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='colorsclothing',
            name='large_category',
        ),
        migrations.AddField(
            model_name='clothing',
            name='large_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainShop.largecategory'),
            preserve_default=False,
        ),
    ]
