# Generated by Django 5.1.1 on 2024-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0006_alter_clothing_image1_alter_clothing_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
