# Generated by Django 5.1.1 on 2024-10-26 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0007_clothing_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='price',
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShop.clothing', verbose_name='Одежда')),
            ],
        ),
    ]
