# Generated by Django 5.1.1 on 2024-10-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0008_remove_clothing_discount_remove_clothing_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='date_order',
            new_name='date_create',
        ),
    ]
