# Generated by Django 5.1.1 on 2024-10-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0009_rename_date_order_pricehistory_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
