# Generated by Django 5.1.1 on 2024-10-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0010_alter_pricehistory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='sizes',
        ),
    ]
