# Generated by Django 5.1.1 on 2024-10-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0011_remove_clothing_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='colors',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название модели'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Бренд', to='MainShop.brand'),
            preserve_default=False,
        ),
    ]
