# Generated by Django 5.1.1 on 2024-10-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0012_brand_remove_clothing_colors_alter_clothing_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='name',
            new_name='model',
        ),
    ]
