# Generated by Django 5.1.1 on 2024-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0013_rename_name_clothing_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренд'},
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='image5',
        ),
        migrations.AddField(
            model_name='stock',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
    ]
