# Generated by Django 5.1.1 on 2024-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShop', '0014_alter_brand_options_remove_clothing_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='sex',
        ),
        migrations.AddField(
            model_name='clothing',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='Средний рейтинг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='target',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс'), ('K', 'Детский')], default=2, max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
